service:
  name: rpg-character-generator

provider:
  name: aws

functions:
  generateCharacter:
    handler: src/index.handler
    runtime: nodejs10.x
    events:
      - http:
          path: v1/generate/character
          method: GET
          integration: lambda
          cors: true